### ISSUE TITLE
Invalid value for 'priority', must be one of '1', '2', '3', '4', '5', '6', '7', '8', '9'

### ISSUE THREAD

**Issue by patriqeso** [crmcarecloud/api-php-client#1]
This is the start point that will cause the problem https://github.com/crmcarecloud/api-php-client/blob/bb318629183dda8172464a31ef4aa3b0412ab820/lib/Api/VouchersApi.php#L837 

Exception `Invalid value for 'priority', must be one of '1', '2', '3', '4', '5', '6', '7', '8', '9'` is thrown there - https://github.com/crmcarecloud/api-php-client/blob/bb318629183dda8172464a31ef4aa3b0412ab820/lib/Model/Reward.php#L744.

I am getting error above when I call this
![exception-trace.png…]()

```php
$careCloud->vouchersApi()->getVouchers(100, 0, null, "DESC", "8e833f19a9379497f18e9df753"
"12969705952",null,null, null, null)
```

**Comment by luboblaho** [comment]
@patriqeso Hello Patrik! Thank you for the issue report! I checked it and figured out this is not a PHP client problem. The problem is how the data for rewards are created in their administration environment. I fixed priority on rewards to the right values. Please check that out now and let me know if it helped. I hope we did not delay your work with this issue.
